language: go
cache:
  directories:
  - ~/libsass
  - ~/sassc
  - ~/bin
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git build-essential
  - test -s ~/libsass || (git clone https://github.com/sass/libsass.git ~/libsass && cd ~/libsass && git checkout tags/3.1.0)
  - test -s ~/sassc || (git clone https://github.com/sass/sassc.git ~/sassc && cd ~/sassc && git checkout tags/3.1.0 && SASS_LIBSASS_PATH=../libsass make)
  - mkdir -p ~/bin
  - ln -s ~/sassc/bin/sassc ~/bin/
  - export PATH=~/bin:$PATH
install: make deps
script: make unittests
