language: go
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git build-essential
  - git clone https://github.com/sass/libsass.git ~/libsass && cd ~/libsass && git checkout tags/3.1.0
  - git clone https://github.com/sass/sassc.git ~/sassc && cd ~/sassc && git checkout tags/3.1.0 && SASS_LIBSASS_PATH=../libsass make
  - mkdir -p ~/bin
  - ln -s ~/sassc/bin/sassc ~/bin/
  # Debugging statements to help with an issue
  - ls -l ~/libsass
  - ls -l ~/sassc
  - ls -l ~/sassc/bin
  - ls -l ~/bin
  - which sassc
install: make deps
script: make unittests
env:
  - PATH=/home/travis/bin/:$PATH
